### ISSUE TITLE
Failed 31 error

### ISSUE THREAD

**Issue by Gamma-Software** [Zarathustra2/TradeRepublicApi#34]
I’ve got an error after setting up the tool:
╰─± python3 ./examples/timelineExporterWithDocsAndDetails.py
Pin:****

*** The process id is: xxxxxxxx-xx-xx-xxxxxxx

ExPrint
Connection Error: failed 31

**Comment by Zarathustra2** [comment]
In the code try to replace:
```python3
await self.ws.send(f"connect 21 {msg}")
```

with 

```python3
await self.ws.send(f"connect 31 {msg}")
```
 and see if that works

**Comment by Gamma-Software** [comment]
Yes @Zarathustra2  that works ;)
